version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npm run dev

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    environment:
      - NODE_ENV=production